get:
  operationId: get_configuration
  x-onedata-gri:
    type: op_provider
    aspect: configuration
  summary: Get public information
  tags:
    - Oneprovider
  x-bash-codegen-description: |
    Returns public information about the Oneprovider service.

    This endpoint does not require authentication.
  description: |
    Returns public information about the Oneprovider service.

    This endpoint does not require authentication.

    ***Example cURL requests***

    **Get public information about the Oneprovider service**
    ```bash
    curl "https://$HOST/api/v3/oneprovider/configuration"

    {
      "providerId": "c4798eb2dbd2486fae940e6fa0a5071d",
      "name": "ProviderName",
      "domain": "zone.domain.org",
      "onezoneDomain": "example.domain.org",
      "version": "R14B04",
      "build": "14-g0d0fd5b",
      "compatibleOnezoneVersions": ["R13B04, R14B04"],
      "compatibleOneproviderVersions": ["R14B04"],
      "compatibleOneclientVersions": ["R14B04"]
    }
    ```
  produces:
    - application/json
  responses:
    '200':
      description: Configuration returned successfully.
      schema:
        $ref: '#/definitions/Configuration'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
