swagger: '2.0'
basePath: /api/v3/oneprovider
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Oneprovider
    description: Information about the Oneprovider service
  - name: Data
    description: Space and file related operations
  - name: Replication
    description: Replication, file distribution and transfer control operations
  - name: Monitoring
    description: Metrics and change events monitoring related operations
x-tagGroups:
  - name: Service information
    tags:
      - Oneprovider
  - name: Data access and management
    tags:
      - Data
  - name: Replication and transfer control
    tags:
      - Replication
  - name: Monitoring and metrics
    tags:
      - Monitoring
securityDefinitions:
  api_key:
    type: apiKey
    name: X-Auth-Token
    in: header
  basic:
    type: basic
security:
  - basic: []
  - api_key: []