swagger: '2.0'
basePath: /api/v3/oneprovider
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Oneprovider
    description: Information about the Oneprovider service
  - name: Space
    description: Spaces related operations
  - name: View
    description: Views related operations
  - name: Resolve File Path
    description: Files and Directories path resolution operations
  - name: Basic File Operations
    description: Files and Directories basic operations
  - name: Custom File Metadata
    description: Files and Directories metadata related operations
  - name: Deprecated File Api
    description: Files and Directories related operations (deprecated)
  - name: QoS
    description: QoS related operations
  - name: Share
    description: Shares related operations
  - name: Replica
    description: Replication and file distribution control operations
  - name: Transfer
    description: Transfers related operations
  - name: Monitoring
    description: Metrics and change events monitoring related operations
x-tagGroups:
  - name: Service information
    tags:
      - Oneprovider
  - name: Space management
    tags:
      - Space
      - View
  - name: File access and management
    tags:
      - Resolve File Path
      - Basic File Operations
      - Custom File Metadata
      - Deprecated File Api
  - name: Replica management
    tags:
      - Replica
      - Transfer
      - QoS
  - name: Share management
    tags:
      - Share
  - name: Monitoring and metrics
    tags:
      - Monitoring
securityDefinitions:
  api_key1:
    type: apiKey
    name: Authorization  # Header value must start with "Bearer "
    in: header
  api_key2:
    type: apiKey
    name: X-Auth-Token
    in: header
security:
  - api_key1: []
  - api_key2: []
  # NOTE: The last key on this list is used by REST-CLI generator as 
  # default authentication method, make sure it's X-Auth-Token
