swagger: '2.0'
basePath: /api/v3/oneprovider
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Oneprovider
    description: Information about the Oneprovider service
  - name: File Path
    description: Files and Directories path related operations
  - name: File Data
    description: Files and Directories data related operations
  - name: File Metadata
    description: Files and Directories metadata related operations
  - name: Deprecated File
    description: Files and Directories related operations (deprecated)
  - name: QoS
    description: QoS related operations
  - name: Share
    description: Shares related operations
  - name: Space
    description: Spaces related operations
  - name: Replica
    description: Replication and file distribution control operations
  - name: Transfer
    description: Transfers related operations
  - name: Monitoring
    description: Metrics and change events monitoring related operations
x-tagGroups:
  - name: Service information
    tags:
      - Oneprovider
  - name: Data access and management
    tags:
      - File Path
      - File Data
      - File Metadata
      - Deprecated File
      - Share
      - Space
  - name: Replication and transfer control
    tags:
      - Replica
      - Transfer
  - name: QoS management
    tags:
      - QoS
  - name: Monitoring and metrics
    tags:
      - Monitoring
securityDefinitions:
  # api_key1 is used by Bash generated clients as default
  # header for sending api key
  api_key1:
    type: apiKey
    name: X-Auth-Token
    in: header
  api_key2:
    type: apiKey
    # When using this method, the token must be prefixed with 'Bearer '
    name: Authorization
    in: header
security:
  - api_key1: []
  - api_key2: []
