type: object
description: >
  Parameters used to configure the process of creating an archive.
properties:
  incremental:
    $ref: '#/definitions/ArchiveIncremental'
  includeDip:
    $ref: '#/definitions/ArchiveIncludeDip'
  layout:
    $ref: '#/definitions/ArchiveLayout'
# TODO VFS-7616 use and rename metadataStructure
#  metadataStructure:
#    $ref: '#/definitions/ArchiveMetadataStructure'
  callback:
    $ref: '#/definitions/ArchivePreservedCallback'
required:
  - incremental
  - includeDip
  - layout
# TODO VFS-7616 use and rename metadataStructure
#  - metadataStructure
  - callback
example:
  incremental: false
  includeDip: false
  layout: bagit
# TODO VFS-7616 use and rename metadataStructure
#  metaDataStructure: json
  callback: "https://example.org/preserved_archives"